### ISSUE TITLE
Results not reproducible

### ISSUE THREAD

**Issue by pthtruc** [gnebehay/OpenTLD#49]
I use opentld.lib (and of course, cvblobs.lib) as static lib in my VS2008 application (I do not use the main.lib and config++.lib). I usually got different results running on the same video sequence several times, i.e., the results were not reproducible, especially when executed outside the VS environment. I believe it is due to the random intialization and random_shuffle(negativeIndices.begin(), negativeIndices.end());

I tried to set srand(0) and create a new TLD() in the beginning of every run but it does not help.
srand(0);
if(myTLD){
	delete myTLD;
	myTLD = new TLD();
}

I also tried with no luck random_shuffle(negativeIndices.begin(), negativeIndices.end(), myrandom);
where myrandom is defined as int myrandom (int i) 
{ 
	static bool seeded = seed();
	return std::rand()%i;
}

Any thoughts, guys? any ...
Thanks you.

**Comment by gnebehay** [comment]
This comment was referring to this post here: http://stackoverflow.com/questions/14221763/stdrandom-shuffle-produces-same-result-each-time , that basically states that the source of randomness for random_shuffle is implementation specific, so the call to srand might not have an effect.
